"""your next change

Revision ID: 7eff61823dd7
Revises: 93f1f03a8e7c
Create Date: 2026-04-29 15:36:50.765543

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eff61823dd7'
down_revision = '93f1f03a8e7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

